package com.roomix.api.model.enums;

public enum DecorationStyle {
    // Styles existants (compatibilité backward)
    SCANDINAVIAN, MODERN_LUXURY, MINIMALIST, JAPANESE_ZEN,
    ARABIC_MODERN, GAMER_SETUP, COZY, INDUSTRIAL,
    SMART_OFFICE, DEVELOPER_SETUP,
    // Nouveaux styles premium
    MODERN, BOHEMIAN, MID_CENTURY, CONTEMPORARY,
    JAPANDI, VINTAGE, MAXIMALIST, NEOCLASSIC,
    FARMHOUSE, SKI_CHALET, ART_DECO, FRENCH_COUNTRY,
    RUSTIC, MEDIEVAL
}
